apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: student-readonly-front
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: APISTUDENTSGROUP
