apiVersion: v1
kind: Secret
metadata:
  name: sqlpassword
type: Opaque
stringData:
  password: your_db_admin_password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: api
  template:
    metadata:
      labels:
        run: api
    spec:
      containers:
        - image: afklmacr8.azurecr.io/yadaapi:1.0
          name: api
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SQL_SERVER_USERNAME
              value: "your_db_admin_username"
            - name: SQL_SERVER_FQDN
              value: "your_db_server_fqdn"
            - name: SQL_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlpassword
                  key: password
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    run: api
